### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HOCMonitor** [SlapBot/stephanie-va#11]
Hello everyone, trying to get Stephanie working on macOS. Everything is working except audio. tts_player is still set to os in the config. I cannot hear anything. Getting this error:
Give me your command!
Default Audio Player for mp3 files is not set up, like vlc or something.

Thanks!

**Comment by Nesh108** [comment]
I had the same problem on Ubuntu and I found out that changing line 15 of `Stephanie/TextManager/speaker.py`

from:
`os.startfile(self.speak_result)`

to:
`os.system("xdg-open " + self.speak_result)`

It seems to work properly (although the mp3 files are being played by my video player). Can you check if that is the same for you? If so, we could add a flag for non-Windows systems.

Actually, since you are on OSX, you should try:

`os.system("open " + self.speak_result)`

**Comment by HOCMonitor** [comment]
@Nesh108 Thank you so much! The bottom line worked!
